name: Run Colab Notebook

on:
  workflow_dispatch:  # Enables manual triggering
  schedule:           # Runs daily at 6 AM UTC
    - cron: '0 0 * * *'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install Jupyter and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert zstandard requests

      # Step 4: Execute the Colab Notebook
      - name: Run Colab Notebook
        run: |
          jupyter nbconvert --execute fetch_parltrack_data.ipynb --to notebook --output executed_notebook.ipynb
