name: Fetch and Upload to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 6 AM UTC

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests zstandard beautifulsoup4 google-api-python-client google-auth google-auth-oauthlib

      - name: Run Fetch and Upload Script
        run: python fetch_and_upload_files.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
