name: Execute Notebook and Upload to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 6 AM UTC

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Jupyter and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert requests zstandard beautifulsoup4 google-api-python-client google-auth google-auth-oauthlib

      # Step 4: Execute the Notebook
      - name: Run Notebook
        run: |
          jupyter nbconvert --to notebook --execute fetch_and_upload_files.ipynb --output executed_notebook.ipynb

      # Step 5: Upload the Executed Notebook as an Artifact
      - name: Upload Executed Notebook
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
