name: Execute Notebook and Upload to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at midnight UTC

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Jupyter and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert requests zstandard beautifulsoup4 google-api-python-client google-auth google-auth-oauthlib

      # Step 4: Write GOOGLE_CREDENTIALS to a temporary file
      - name: Write Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/credentials.json
        shell: bash

      # Step 5: Execute the Notebook
      - name: Run Notebook
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json \
          jupyter nbconvert --to notebook --execute fetch_parltrack_data.ipynb --output executed_notebook.ipynb
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          
      # Step 6: Upload the Executed Notebook as an Artifact
      - name: Upload Executed Notebook
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb

      # Step 7: Upload the log file as an artifact
      - name: Upload Log File
        uses: actions/upload-artifact@v3
        with:
          name: process-log
          path: /tmp/fetch_and_upload_log_*.txt

      # Step 8: Cleanup Temporary Credentials
      - name: Cleanup
        run: rm -f /tmp/credentials.json
